pool:
  name: aws
  demands: java

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    # gradleWrapperFile: '$(Parameters.wrapperScript)'
    gradleWrapperFile: "gradlew"
    tasks: '$(Parameters.tasks)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()